### ISSUE TITLE
wg-server udp port 51820 open to 0.0.0.0/0

### ISSUE THREAD

**Issue by farooqdevops** [jmhale/terraform-aws-wireguard#24]
Hi
i have to ask two things:
1. Regarding wireguard-server, we configure a security group which allows everyone to connect on udp port 51820. Is it needed by design or can we avoid this open udp port for everyone. How much is this insecure then?

2. what does %i here means when we add iptables command:
`PostUp   = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE`

 Thanks

**Comment by atrull** [comment]
Needed by design. This is an ACCESS VPN server. Clients come from anywhere. The security is handled by the authentication,  not the network.

**Comment by atrull** [comment]
the %i is for wireguard to put in its own wireguard interface in the iptables commands .. typically this is wg0

**Comment by jmhale** [comment]
@atrull is correct on both counts. 

If desired, the Security Group allowing connections to Wireguard can be modified to allow specific IPs [here](https://github.com/jmhale/terraform-aws-wireguard/blob/master/wireguard-securitygroups.tf#L17), but that's an edge case, given the purpose of Wireguard and is outside the scope of this project.

Since there's no action to take, I'm going to close this.
